---
version: '3'
services:
  maven:
    build: maven
    volumes:
      - dataapp:/origin556/target
      - configfile:/origin556/config
    depends_on:
      - mysql
  tomcat:
    image: tomcat:jdk8-openjdk
    volumes:
      - dataapp:/usr/local/tomcat/webapps
      - configfile:/usr/local/tomcat/ROOT
    ports:
      - 8080:8080
    depends_on:
      - maven

  mysql:
    image: mysql:5
    hostname: database
    restart: always
    environment:
      - MYSQL_DATABASE=appdatabase
      - MYSQL_ROOT_PASSWORD=qwerty
    ports:
      - '3306:3306'
    volumes:
      - ./src/main/db:/docker-entrypoint-initdb.d/:ro
      - ./data:/var/lib/mysql

volumes:
  dataapp:
  configfile:
