---
version: '3'
services:
  maven:
    build: maven
    volumes:
      - dataapp:/App42PaaS-Java-MySQL-Sample/target

  tomcat:
    image: tomcat:8-jre8
    volumes:
      - dataapp:/usr/local/tomcat/webapps
    ports:
      - 8080:8080
    depends_on:
      - maven

  mysql:
    image: mysql
    volumes:
      - dataapp:/usr/local/tomcat/webapps

volumes:
  dataapp: