---
version: '3'
services:
  maven:
    build: maven
    volumes:
      - dataapp:/App42PaaS-Java-MySQL-Sample/target
    depends_on:
      - mysql
  tomcat:
    image: tomcat:6.0.16
    volumes:
      - dataapp:/usr/local/tomcat/webapps
    ports:
      - 8080:8080
    depends_on:
      - maven

  mysql:
    image: mysql:5.1.8
    restart: always
    enviroment:
      - MYSQL_DATABASE=appdatabase
      - MYSQL_ROOT_PASSWORD=qwerty
    ports:
      - '3306:3306'
    volumes:
      - .:/docker-entrypoint-initdb.d

volumes:
  dataapp:
  db:
    driver: local