---
version: '3'
services:
  maven:
    build: maven
    volumes:
      - dataapp:/origin556/target
    depends_on:
      - mysql
  tomcat:
    build: tomcat
    volumes:
      - dataapp:/usr/local/tomcat/webapps
    ports:
      - 8080:8080
    depends_on:
      - maven

  mysql:
    image: mysql:5
    hostname: database
    restart: always
    environment:
      - MYSQL_DATABASE=appdatabase
      - MYSQL_ROOT_PASSWORD=qwerty
    ports:
      - '3306:3306'
    volumes:
      - ./src/main/db:/docker-entrypoint-initdb.d/:ro
      - ./data:/var/lib/mysql

volumes:
  dataapp:
